FROM gcr.io/fivetran-donkeys/zulu-openjdk:17.0.7-17.42.19

COPY run_sdk_connector_tester_deploy.jar /app/SdkConnectorTester.jar

# /data folder will get mapped externally when the image is run

EXPOSE 50051

ENTRYPOINT ["java", "-jar", "/app/SdkConnectorTester.jar", "--working-dir=/data"]
