FROM us-docker.pkg.dev/build-286712/prod-docker-us/base_images/zulu-openjdk:17.0.9-17.46.19

COPY run_sdk_connector_tester_deploy.jar /app/SdkConnectorTester.jar

# /data folder will get mapped externally when the image is run

EXPOSE 50051

ENTRYPOINT ["java", "-jar", "/app/SdkConnectorTester.jar", "--working-dir=/data"]
