FROM azul/zulu-openjdk:17.0.8.1-17.44.53

COPY run_sdk_connector_tester_deploy.jar /app/SdkConnectorTester.jar

# /data folder will get mapped externally when the image is run

EXPOSE 50051

ENTRYPOINT ["java", "-jar", "/app/SdkConnectorTester.jar", "--working-dir=/data"]
